[package]
name = "cellular_automata"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.10"
log = "0.4"
wgpu = "22.0"
tokio = { version = "1", features = ["full"] }
# sdl2 = "0.37.0"
